# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: set paths
          command: 'echo "export PATH=$HOME/.cargo/bin:$PATH" >> $BASH_ENV'
      - run:
          name: install rust
          command: 'curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && cargo version'
      - run:
          name: test
          command: 'make -C test/ circle-ci'

