---
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust:1.41.0
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: 'build'
          command: 'make build'
      - run:
          name: '[host test] debian stretch'
          command: 'make test-host-debian-stretch'
      - run:
          name: '[host test] ubuntu bionic'
          command: 'make test-host-ubuntu-bionic'
      - run:
          name: '[host test] python3.6'
          command: 'make test-host-python-3.6'
      - run:
          name: '[docker test] ubuntu bionic'
          command: 'make test-docker-ubuntu-bionic'
      - run:
          name: '[docker test] debian stretch'
          command: 'make test-docker-debian-stretch'
      - run:
          name: '[docker test] alpine 3.11'
          command: 'make test-docker-alpine-3.11'
      - run:
          name: '[docker test] python3.6'
          command: 'make test-docker-python-3.6'
