---
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust:1.41.0
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build
          command: 'make build'
      - run:
          name: test centos 8
          command: 'make test-centos-8'
      - run:
          name: test ubuntu bionic
          command: 'make test-ubuntu-bionic'
      - run:
          name: test debian stretch
          command: 'make test-debian-stretch'
      - run:
          name: test python 3.6
          command: 'make test-python-3.6'

