---
version: 2.1
jobs:
  build:
    docker:
      - image: quay.io/fishi/rakn-test-images:debian-stretch
    steps:
      - checkout
      - run:
          name: set paths
          command: 'echo "export PATH=$HOME/.cargo/bin:$PATH" >> $BASH_ENV'
      - run:
          name: prepare venv
          command: 'make -C tests/ venv'
      - run:
          name: test
          command: 'make -C tests/ circle-ci-integration-test'

