---
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust:1.41.0
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: '[cargo test]'
          command: 'make test'
      - run:
          name: '[host test] debian stretch'
          command: 'make test-host-debian-stretch'
      - run:
          name: '[host test] ubuntu bionic'
          command: 'make test-host-ubuntu-bionic'
      - run:
          name: '[host test] python3.6'
          command: 'make test-host-python-3.6'
